version: '3.8'

services:
  api:
    image: fabandalm/stock-smart-ai-api:1.0.0
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:12.6
    container_name: stock-smart-ai-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - app-network

  ui:
    image: fabandalm/stock-smart-ai-ui:1.0.0
    container_name: stock-smart-ai-ui
    ports:
      - "3000:3000"
    volumes:
      - ./path-to-your-react-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - api

volumes:
  postgres-volume:

networks:
  app-network:
    driver: bridge
