version: '3.8'

services:
  api:
    image: fabandalm/stock-smart-ai-api:1.0.0
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: postgres:12.6
    container_name: stock-smart-ai-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-volume:

networks:
  app-network:
    driver: bridge
