apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-smart-ai-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-smart-ai-ui
  template:
    metadata:
      labels:
        app: stock-smart-ai-ui
    spec:
      containers:
        - name: ui
          image: fabandalm/stock-smart-ai-ui:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ui-config
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5