INSERT INTO category (name, description) VALUES
 ('Electronics', 'Devices and gadgets including smartphones, laptops, and accessories'),
 ('Clothing', 'Men and women apparel, footwear, and accessories'),
 ('Home & Kitchen', 'Appliances, furniture, and decor for home and kitchen'),
 ('Books', 'Fiction, non-fiction, textbooks, and reference books'),
 ('Toys & Games', 'Board games, action figures, puzzles, and educational toys'),
 ('Sports & Outdoors', 'Equipment, apparel, and accessories for sports and outdoor activities'),
 ('Beauty & Personal Care', 'Cosmetics, skincare, and grooming products'),
 ('Health & Wellness', 'Supplements, fitness gear, and medical supplies'),
 ('Automotive', 'Car accessories, tools, and maintenance equipment'),
 ('Jewelry & Watches', 'Rings, necklaces, watches, and other accessories'),
 ('Grocery', 'Food items, beverages, and pantry staples'),
 ('Pet Supplies', 'Food, toys, and accessories for pets'),
 ('Office Supplies', 'Stationery, printers, and office essentials'),
 ('Music Instruments', 'Guitars, keyboards, drums, and other musical instruments'),
 ('Movies & TV', 'DVDs, Blu-rays, and streaming subscriptions'),
 ('Gaming', 'Video games, consoles, and gaming accessories'),
 ('Baby Products', 'Diapers, baby food, toys, and essentials for infants'),
 ('Garden & Outdoors', 'Plants, gardening tools, and outdoor furniture'),
 ('Industrial & Scientific', 'Lab equipment, industrial tools, and research materials'),
 ('Furniture', 'Living room, bedroom, and office furniture'),
 ('Handmade', 'Custom and handmade crafts, gifts, and artwork'),
 ('Luggage & Travel', 'Suitcases, backpacks, and travel accessories'),
 ('Collectibles & Memorabilia', 'Rare items, vintage collections, and autographs'),
 ('Photography', 'Cameras, lenses, tripods, and accessories'),
 ('Smart Home', 'Home automation devices, security cameras, and smart assistants'),
 ('Wearable Technology', 'Smartwatches, fitness trackers, and AR/VR devices'),
 ('Art & Crafts', 'Painting, knitting, DIY kits, and art supplies'),
 ('Bicycles & Accessories', 'Bicycles, helmets, and biking gear'),
 ('Luxury Items', 'High-end fashion, jewelry, and accessories');